# 指定项目端口号
server:
  port: 9101

spring:
  application:
    name: ms-user-service
    
  datasource:    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emart?useSSL=false&useUnicode=true&characterEncoding=utf8&&serverTimezone=UTC
    
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
#    properties:#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate: 
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

